# Site
name: "Ça Vaud le détour"
title: "Ça Vaud le détour"
description: "Découverte du pays vaudois au travers des yeux d'une famille expatriée en Suisse..."
logo: 'assets/images/cvd-logo.png'
favicon: 'assets/images/cvd-logo.png'
baseurl: /ca-vaud-le-detour
google_analytics: 'UA-46278016-1'
disqus: 'ca-vaud-le-detour'
mailchimp-list: false
include: ["_pages"]
permalink: /:title/
default_locale: "fr"

# Authors
authors:
  guillaume:
    name: Guillaume
    display_name: Guillaume
    avatar: assets/images/avatar-guillaume.png
    email: contact@gguerin.fr
    web: http://deeder.fr
    twitter: https://twitter.com/Deeder
    description: "Ingénieur, touche à tout et baroudeur."
  oceane:
    name: Océane
    display_name: Océ
    avatar: 'assets/images/avatar-oceane.png'
    email: o.quincy@gmail.com
    description: 'Maman, voyageuse et curieuse.'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
